import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Header from "../../components/Header";
import { useEffect } from "react";
import PhotoCard from "../../components/PhotoCard";

export default function Album({ photos }) {
  return (
    <div>
      <Head>
        <title>Photo Album Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <h3 data-testid="album-title">Album {photos[0].albumId}</h3>

      <main data-testid="main-content" className={styles.main}>
        {photos.map((photo, i) => (
          <PhotoCard {...photo} key={i} />
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

// serverside data fetching
export async function getServerSideProps({ params }) {
  // Fetch data from external API
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/photos?albumId=${params.id}`
  );
  const photos = await res.json();

  // Pass data to the page via props
  return { props: { photos } };
}
