import styles from "../../styles/Album.module.css";
import Head from "next/head";
import Header from "../../components/Header";
import PhotoCard from "../../components/PhotoCard";

export default function Album({ photos }) {
  return (
    <div>
      <Head>
        <title>Album {photos[0].albumId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main data-testid="main-content" className={styles.main}>
        <h3 data-testid="album-title" className={styles.albumTitle}>
          Album {photos[0].albumId}
        </h3>
        <div className={styles.mainContent}>
          {photos.map((photo, i) => (
            <PhotoCard {...photo} key={i} />
          ))}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

// serverside data fetching
export async function getServerSideProps({ params }) {
  // Fetch data from external API
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/photos?albumId=${params.id}`
  );
  const photos = await res.json();

  // Pass data to the page via props
  return { props: { photos } };
}
