import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Header from "../../components/Header";

export default function Album() {
  return (
    <div>
      <Head>
        <title>Photo Album Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main data-testid="main-content" className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
